// Permission presets keyed by autonomy level. Each AI tool spells permissions
// differently, so this module exposes one function per tool config format,
// all driven by the same three-level model:
//   cautious   — read freely, ask before anything else (best for beginners)
//   balanced   — common safe commands pre-approved, edits auto-accepted
//   autonomous — broad allowlist for users who review diffs afterwards

const SAFE_READ = [
  'Bash(ls:*)',
  'Bash(git status:*)',
  'Bash(git diff:*)',
  'Bash(git log:*)',
];

const COMMON_DEV = [
  'Bash(git add:*)',
  'Bash(git commit:*)',
  'Bash(npm test:*)',
  'Bash(npm run:*)',
  'Bash(node:*)',
];

const DENY_SECRETS = [
  'Read(./.env)',
  'Read(./.env.*)',
  'Read(./secrets/**)',
  'Read(**/*.pem)',
  'Read(**/id_rsa*)',
];

/** Settings fragment for Claude Code settings.json (merged, never replaced). */
export function claudeSettings(profile) {
  const autonomy = profile.autonomy;
  const allow =
    autonomy === 'cautious'
      ? SAFE_READ
      : autonomy === 'balanced'
        ? [...SAFE_READ, ...COMMON_DEV]
        : [...SAFE_READ, ...COMMON_DEV, 'Bash(git push:*)', 'WebFetch'];

  const settings = {
    permissions: {
      allow,
      deny: DENY_SECRETS,
    },
  };
  if (autonomy !== 'cautious') {
    settings.permissions.defaultMode = 'acceptEdits';
  }
  return settings;
}

/** Full config.toml for Codex CLI (written only when none exists). */
export function codexConfigToml(profile) {
  const autonomy = profile.autonomy;
  const approval =
    autonomy === 'cautious'
      ? 'untrusted'
      : autonomy === 'balanced'
        ? 'on-request'
        : 'on-failure';
  const sandbox = autonomy === 'cautious' ? 'read-only' : 'workspace-write';

  return [
    '# Generated by agent-primer (written once; edit freely, re-runs will not overwrite)',
    `approval_policy = "${approval}"`,
    `sandbox_mode = "${sandbox}"`,
    '',
  ].join('\n');
}
